### ISSUE TITLE
p2p unitTest case: Send message to a remote endpoint should be resolved.  failed

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#310]
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at s._timeoutError (https://cdnjs.cloudflare.com/ajax/libs/mocha/5.2.0/mocha.min.js:1:40654)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/5.2.0/mocha.min.js:1:38785

**Comment by jianjunz** [comment]
Cannot reproduce. This case could be passed.
